# Generated by Django 2.0.10 on 2019-03-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteapiuser',
            name='is_ldap_account',
            field=models.BooleanField(default=False),
        ),
    ]
