# Generated by Django 3.2.9 on 2022-04-05 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiauth', '0002_remoteapiuser_is_ldap_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remoteapiuser',
            name='email',
        ),
    ]
