# Generated by Django 3.2.12 on 2022-04-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiauth', '0003_remove_remoteapiuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteapiuser',
            name='remote_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
