# Generated by Django 3.2.12 on 2022-04-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiauth', '0004_remoteapiuser_remote_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteapiuser',
            name='remote_id',
            field=models.IntegerField(unique=True),
        ),
    ]
